name: atacseq-unmc
channels:
  - rapidsai
  - conda-forge
  - nvidia
  - bioconda
  - defaults
dependencies:
  - python=3.8
  - pip=23.1.2
  - ipykernel=6.23.3
  - matplotlib=3.7.1
  - gsutil=5.25
  - pandas=1.5.3
  - fastqc=0.12.1
  - multiqc=1.14
  - trimmomatic=0.39
  - bowtie2=2.5.1
  - samtools=1.17
  - picard=3.0.0
  - ncurses=6.4
  - deeptools=3.5.2
  - macs2=2.2.7.1
  - homer=4.11
  - cudatoolkit=11.8
  - rapids=22.12
  - cuml=22.12
  - cudf=22.12
  - rmm=22.12
  - numba=0.56.4
  - cupy=11.6.0
  - scanpy=1.9.3
  - anndata=0.9.1
  - pip:
      - jupyterquiz==2.0.7
      - jupytercards==2.1
      - igv-notebook==0.5.2
      - tobias==0.15.1
      - manorm==1.3.0
      - adjustText==0.7.3